[env:m5stickc_plus]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = default.csv
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.psram_type = qio
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
	m5stack/M5StickCPlus@^0.1.1
	esphome/ESP32-audioI2S@^2.3.0
	earlephilhower/ESP8266Audio@^1.9.0
